[package]
name = "number_seracher_workspace"
version = "0.1.0"
edition = "2021"
authors = ["Alex_Xar <P40b0s@gmail.com>"]

[workspace]
members = [ "extractors",
    "src-tauri",
]
default-members = ["src-tauri"]



[dependencies]



